"""empty message

Revision ID: 131325365824
Revises: fd9ec76dcb37
Create Date: 2023-06-12 11:56:09.459296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131325365824'
down_revision = 'fd9ec76dcb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_song_table',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_constraint('song_user_fkey', type_='foreignkey')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('song_user_fkey', 'user', ['user'], ['id'])

    op.drop_table('user_song_table')
    # ### end Alembic commands ###
