"""empty message

Revision ID: 1d9e179aa6d1
Revises: 0c54ed2b9d81
Create Date: 2023-06-24 09:55:07.955438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9e179aa6d1'
down_revision = '0c54ed2b9d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('song_genre_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'genre', ['genre_id'], ['id'])
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('song_genre_fkey', 'genre', ['genre'], ['id'])
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###
