"""empty message

Revision ID: 5d29d38ff06d
Revises: 80e4139b48af
Create Date: 2023-06-14 20:05:48.094946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d29d38ff06d'
down_revision = '80e4139b48af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('len_love_song', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('len_love_song')

    # ### end Alembic commands ###
