"""empty message

Revision ID: 7ab895b5f3a5
Revises: 17bfc5a71133
Create Date: 2023-06-24 09:28:28.306239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab895b5f3a5'
down_revision = '17bfc5a71133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('genre')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_constraint('song_genre_fkey', type_='foreignkey')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('song_genre_fkey', 'genre', ['genre'], ['id'])

    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='genre_pkey')
    )
    # ### end Alembic commands ###
